Update VagrantLinux3

diff --git a/VagrantLinux3 b/VagrantLinux3
--- a/VagrantLinux3
+++ b/VagrantLinux3
@@ -1,4 +1,21 @@
 #!/bin/bash
+if [$(id - u) -eq0]: then
+   read-p "Enter username : " username
+   read-s-p "Enter password: " password
+   egrep "^$username" /etc/passwd >/dev/null
+if [$?-eq0]; then
+   echo "$username exists!"
+   exit 1
+else
+   pass=$(perl -e 'print cyrpt($ARGV[0], "password")'$password)
+   useradd -m-p $pass$username 
+   [$?-eq0]&&echo "User has been added to system!"|| echo "Fail to add a user!"
+  fl
+else
+   echo "Only root may add a user to the system"
+fl   
+
+#!/bin/bash
 while [ true ] ;do
 used=`free -m |awk 'NR==3 {print $4}'`
 if [ $used -lt 1500 ] && [ $used -gt 800 ]; then
@@ -8,37 +25,7 @@ fi
 sleep 5
 done
 
-Next script will display your system information.
-#!/bin/bash
-# Sample script written for Part 4 of the RHCE series
-# This script will return the following set of system information:
-# -Hostname information:
-echo -e "\e[31;43m***** HOSTNAME INFORMATION *****\e[0m"
-hostnamectl
-echo ""
-# -File system disk space usage:
-echo -e "\e[31;43m***** FILE SYSTEM DISK SPACE USAGE *****\e[0m"
-df -h
-echo ""
-# -Free and used memory in the system:
-echo -e "\e[31;43m ***** FREE AND USED MEMORY *****\e[0m"
-free
-echo ""
-# -System uptime and load:
-echo -e "\e[31;43m***** SYSTEM UPTIME AND LOAD *****\e[0m"
-uptime
-echo ""
-# -Logged-in users:
-echo -e "\e[31;43m***** CURRENTLY LOGGED-IN USERS *****\e[0m"
-who
-echo ""
-# -Top 5 processes as far as memory usage is concerned
-echo -e "\e[31;43m***** TOP 5 MEMORY-CONSUMING PROCESSES *****\e[0m"
-ps -eo %mem,%cpu,comm --sort=-%mem | head -n 6
-echo ""
-echo -e "\e[1;32mDone.\e[0m"
 
-Next script will run the well-known df -h command, format the output into a HTML table and save it in the report.html file. When you run this script, you will get an error message that no directory exists for storing report.html file. Fix this error by specifying a different path inside your script (you can choose the same path where all of your scripts are stored).
 #!/bin/bash
 # Sample script to demonstrate the creation of an HTML report using shell scripting
 # Web directory
@@ -75,5 +62,3 @@ echo $line | awk '{print $5}' >> $WEB_DIR/report.html
 echo "</tr>" >> $WEB_DIR/report.html
 done < <(df -h | grep -vi filesystem)
 echo "" >> $WEB_DIR/report.html
-
-## big test......are younusing Brackets?
